### ISSUE TITLE
The version of a MISP cluster has the type INT.

### ISSUE THREAD

**Issue by jloehel** [malicialab/avclass#42]
I can not add the current `master` to MISP. The version of the MISP cluster should be an integer and not a string.

Traceback:
~~~Shell
$ sudo -u misp /var/www/MISP-2.4.169/app/Console/cake Admin updateGalaxies                                                                                                                
Error: SQLSTATE[01000]: Warning: 1265 Data truncated for column 'version' at row 1                                                                                                            
#0 /var/www/MISP-2.4.169/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)                                                                           
#1 /var/www/MISP-2.4.169/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('INSERT INTO `mi...', Array)                                                       
#2 /var/www/MISP-2.4.169/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute('INSERT INTO `mi...')                                                              
#3 /var/www/MISP-2.4.169/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create(Object(GalaxyCluster), Array, Array)                                                               
#4 /var/www/MISP-2.4.169/app/Lib/cakephp/lib/Cake/Model/Model.php(1754): Model->_doSave(Array, Array)                                                                                         
#5 /var/www/MISP-2.4.169/app/Model/Galaxy.php(190): Model->save(Array, Array)                                                                                                                 
#6 /var/www/MISP-2.4.169/app/Model/Galaxy.php(261): Galaxy->__createClusters(Array, Array)                                                                                                    
#7 /var/www/MISP-2.4.169/app/Console/Command/AdminShell.php(286): Galaxy->update(false)                                                                                                       
#8 /var/www/MISP-2.4.169/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): AdminShell->updateGalaxies()                                                                                        
#9 /var/www/MISP-2.4.169/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand('updateGalaxies', Array)                                                                
#10 /var/www/MISP-2.4.169/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()                                                                               
#11 /var/www/MISP-2.4.169/app/Console/cake.php(45): ShellDispatcher::run(Array)                                                                                                               
#12 {main}
~~~

https://github.com/malicialab/avclass/blob/58ae3db263046a6ac03ed182354509f09603e19b/avclass/data/misp/cluster/avclass.json#L13322

~~~
mysql> describe galaxy_clusters;
+------------------+--------------+------+-----+---------+----------------+
| Field            | Type         | Null | Key | Default | Extra          |
+------------------+--------------+------+-----+---------+----------------+
| id               | int          | NO   | PRI | NULL    | auto_increment |
...
| version          | int          | YES  | MUL | 0       |                | 
...
~~~

**Comment by malicialab** [comment]
I have removed semantic versioning and moved to sequential version numbers and assigned the current version number 2
If that works, please close the issue. If you run into other issues importing it, let me know.

**Comment by jloehel** [comment]
> I have removed semantic versioning and moved to sequential version numbers and assigned the current version number 2 If that works, please close the issue. If you run into other issues importing it, let me know.

Works for me. Thanks. I will close the issue.
