### ISSUE TITLE
Bug when using -d option

### ISSUE THREAD

**Issue by CassieXx0215** [malicialab/avclass#44]
When I use the `-d` option to give a directory of multiple files, it gives the following error:
```
[-] Using tagging rules in /home/cassie/.local/lib/python3.10/site-packages/avclass/data/default.tagging
[-] Using taxonomy in /home/cassie/.local/lib/python3.10/site-packages/avclass/data/default.taxonomy
[-] Using expansion tags in /home/cassie/.local/lib/python3.10/site-packages/avclass/data/default.expansion
Traceback (most recent call last):
  File "/home/cassie/.local/bin/avclass", line 8, in <module>
    sys.exit(main())
  File "/home/cassie/.local/lib/python3.10/site-packages/avclass/labeler.py", line 501, in main
    args, ifile_l = parse_args()
  File "/home/cassie/.local/lib/python3.10/site-packages/avclass/labeler.py", line 680, in parse_args
    files.add(filepath)
AttributeError: 'dict' object has no attribute 'add'
```
It tracks down to this part (lines 672 to 683) in `labeler.py`
```
    # Build list of input files
    files = set(args.f) if args.f is not None else {}
    if args.d:
        for d in args.d:
            if os.path.isdir:
                for f in os.listdir(d):
                    filepath = os.path.join(d, f)
                    if os.path.isfile(filepath):
                        files.add(filepath)
            else:
                log.warning('Not a valid directory: %s' % d)
                sys.exit(1)
```
Files should be initialized as an empty set when args.f is None, not an empty dictionary. 
(When I use -f together with -d, it doesn't give the error, as files is correctly initialized as a set. )

**Comment by CassieXx0215** [comment]
> Indeed, should have tested that refactoring better. I just pushed version 2.8.3 to PyPI that should fix it. If that fixes it for you, please close the issue. Otherwise, let me know Thanks!

Yes, have tested and that fixes the problem. Thanks for the quick reply!
I'm closing the issue now.
